// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCPQoj2rr22Lh2cB4VbPrQMKhc2H4Zb6lg',
    appId: '1:458823860437:web:902e4e0fbe1ea7031fe25c',
    messagingSenderId: '458823860437',
    projectId: 'flutter-crud-90e5b',
    authDomain: 'flutter-crud-90e5b.firebaseapp.com',
    storageBucket: 'flutter-crud-90e5b.appspot.com',
    measurementId: 'G-E4KHKP0GRS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCR-fL8zLBaWkMCDlguGFVnSIw6JVrp_YU',
    appId: '1:458823860437:android:6d018883d03eea231fe25c',
    messagingSenderId: '458823860437',
    projectId: 'flutter-crud-90e5b',
    storageBucket: 'flutter-crud-90e5b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBog5BrabUsfaksg6k03TS-9-VSwRPIjOs',
    appId: '1:458823860437:ios:33aabe390caad9e11fe25c',
    messagingSenderId: '458823860437',
    projectId: 'flutter-crud-90e5b',
    storageBucket: 'flutter-crud-90e5b.appspot.com',
    iosBundleId: 'com.example.flutterApplicationConFirebase',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBog5BrabUsfaksg6k03TS-9-VSwRPIjOs',
    appId: '1:458823860437:ios:33aabe390caad9e11fe25c',
    messagingSenderId: '458823860437',
    projectId: 'flutter-crud-90e5b',
    storageBucket: 'flutter-crud-90e5b.appspot.com',
    iosBundleId: 'com.example.flutterApplicationConFirebase',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCPQoj2rr22Lh2cB4VbPrQMKhc2H4Zb6lg',
    appId: '1:458823860437:web:055e25aebed217a41fe25c',
    messagingSenderId: '458823860437',
    projectId: 'flutter-crud-90e5b',
    authDomain: 'flutter-crud-90e5b.firebaseapp.com',
    storageBucket: 'flutter-crud-90e5b.appspot.com',
    measurementId: 'G-L5HM6YBSN1',
  );
}
